import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css"; // This will be generated by Tailwind during build

const root = createRoot(document.getElementById("root"));
root.render(<App />);
